apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-service
  template:
    metadata:
      labels:
        app: micro-service
    spec:
      containers:
      - name: micro-service
        image: avyukth/micro-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: micro-service
spec:
  selector:
    app: micro-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
